name: Test_Artifact_V3
on: workflow_dispatch
jobs:
  Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create large file
      run: |
        mkdir content
        cd content
        head -c 100000000 </dev/urandom >file1.zip
        cd ..
    - name: Upload First
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: |
          /content/*
        retention-days: 1
  
  
  
